export enum AuthErrorCode {
  MAX_SESSIONS_EXCEEDED = 'MAX_SESSIONS_EXCEEDED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  REFRESH_TOKEN_INVALID = 'REFRESH_TOKEN_INVALID',
  REFRESH_TOKEN_MISSING = 'REFRESH_TOKEN_MISSING',
  SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',
  SESSION_MISMATCH = 'SESSION_MISMATCH',
  EMAIL_NOT_CONFIRMED = 'EMAIL_NOT_CONFIRMED',
  USER_DEACTIVATED = 'USER_DEACTIVATED',
}

export enum SecurityErrorCode {
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  LOGIN_RATE_LIMIT = 'LOGIN_RATE_LIMIT',
  PASSWORD_RESET_RATE_LIMIT = 'PASSWORD_RESET_RATE_LIMIT',
  DEACTIVATION_RATE_LIMIT = 'DEACTIVATION_RATE_LIMIT',
}

export enum MediaErrorCode {
  AVATAR_INVALID_FORMAT = 'AVATAR_INVALID_FORMAT',
  AVATAR_PROCESSING_ERROR = 'AVATAR_PROCESSING_ERROR',
  AVATAR_NOT_FOUND = 'AVATAR_NOT_FOUND',
  WRONG_TYPE = 'WRONG_TYPE',
  NO_ACCESS = 'NO_ACCESS',
  IMG_NOT_FOUND = 'IMG_NOT_FOUND',
  MAX_LOT_IMG = 'MAX_LOT_IMG',
}
