export enum AuthErrorCode {
  MAX_SESSIONS_EXCEEDED = 'MAX_SESSIONS_EXCEEDED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  REFRESH_TOKEN_INVALID = 'REFRESH_TOKEN_INVALID',
  REFRESH_TOKEN_MISSING = 'REFRESH_TOKEN_MISSING',
  SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',
  SESSION_MISMATCH = 'SESSION_MISMATCH',
  EMAIL_NOT_CONFIRMED = 'EMAIL_NOT_CONFIRMED',
}

export enum SecurityErrorCode {
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  LOGIN_RATE_LIMIT = 'LOGIN_RATE_LIMIT',
}
