export enum OfferErrorCode {
  OFFER_NOT_FOUND = 'OFFER_NOT_FOUND',
  TARGET_LOT_NOT_FOUND = 'TARGET_LOT_NOT_FOUND',
  TARGET_LOT_INACTIVE = 'TARGET_LOT_INACTIVE',
  SELF_OFFER_NOT_ALLOWED = 'SELF_OFFER_NOT_ALLOWED',
  OFFERED_LOTS_INVALID = 'OFFERED_LOTS_INVALID',
  OFFERED_LOT_NOT_PREFERRED = 'OFFERED_LOT_NOT_PREFERRED',
  DUPLICATE_OFFER = 'DUPLICATE_OFFER',
  MIRROR_OFFER_EXISTS = 'MIRROR_OFFER_EXISTS',
  OFFER_COOLDOWN = 'OFFER_COOLDOWN',
  OFFER_FORBIDDEN = 'OFFER_FORBIDDEN',
  INVALID_STATUS_TRANSITION = 'INVALID_STATUS_TRANSITION',
}
