export enum UserErrorCode {
  // Общие
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_DEACTIVATED = 'USER_DEACTIVATED',

  // Регистрация / профиль
  EMAIL_ALREADY_IN_USE = 'EMAIL_ALREADY_IN_USE',
  LOGIN_ALREADY_IN_USE = 'LOGIN_ALREADY_IN_USE',

  // Связи
  COUNTRY_NOT_FOUND = 'COUNTRY_NOT_FOUND',

  // Бизнес-инварианты
  LAST_ADMIN_DEACTIVATION_FORBIDDEN = 'LAST_ADMIN_DEACTIVATION_FORBIDDEN',

  // География
  REGION_NOT_FOUND = 'REGION_NOT_FOUND',
  CITY_NOT_FOUND = 'CITY_NOT_FOUND',
  DISTRICT_NOT_FOUND = 'DISTRICT_NOT_FOUND',
}
