# ---------- DEV ----------
FROM node:20-alpine AS dev

WORKDIR /app

COPY server/package*.json ./
RUN npm ci

CMD ["npm", "run", "start:dev"]


# ---------- BUILD ----------
FROM node:20-alpine AS builder

WORKDIR /app

COPY server/package*.json ./
RUN npm ci

COPY server ./
RUN npm run build
RUN npm prune --production


# ---------- PROD ----------
FROM node:20-alpine AS prod

WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/src/database/seeds ./src/database/seeds
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules

CMD ["node", "dist/main.js"]
