import {
  Baby,
  BriefcaseBusiness,
  Building2,
  Car,
  CircleEllipsis,
  Cpu,
  Dumbbell,
  Hammer,
  HeartPulse,
  House,
  Laptop,
  PartyPopper,
  PawPrint,
  Shirt,
  ShirtIcon,
  Smartphone,
  Sofa,
  Trees,
  WashingMachine,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export const chapterIcons: Record<string, LucideIcon> = {
  nedvizhimost: Building2,
  'auto-i-zapchasti': Car,
  'bytovaya-tehnika': WashingMachine,
  'kompyuternaya-tekhnika': Laptop,
  'telefony-i-planshety': Smartphone,
  elektronika: Cpu,
  'zhenskiy-garderob': Shirt,
  'muzhskoy-garderob': ShirtIcon,
  'beauty-health': HeartPulse,
  'kids-moms': Baby,
  furniture: Sofa,
  home: House,
  construction: Hammer,
  'garden-and-garden': Trees,
  'hobby-sports-tourism': Dumbbell,
  'weddings-holidays': PartyPopper,
  animals: PawPrint,
  'business-equipment': BriefcaseBusiness,
  other: CircleEllipsis,
};
