export const ERROR_TYPES = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_NOT_CONFIRMED: 'EMAIL_NOT_CONFIRMED',
  MAX_SESSIONS_EXCEEDED: 'MAX_SESSIONS_EXCEEDED',
  LOGIN_RATE_LIMIT: 'LOGIN_RATE_LIMIT',
  EMAIL_ALREADY_IN_USE: 'EMAIL_ALREADY_IN_USE',
  LOGIN_ALREADY_IN_USE: 'LOGIN_ALREADY_IN_USE',
  COUNTRY_NOT_FOUND: 'COUNTRY_NOT_FOUND',
  REGION_NOT_FOUND: 'REGION_NOT_FOUND',
  CITY_NOT_FOUND: 'CITY_NOT_FOUND',
  DISTRICT_NOT_FOUND: 'DISTRICT_NOT_FOUND',
  CHAPTER_NOT_FOUND: 'CHAPTER_NOT_FOUND',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  SUBCATEGORY_REQUIRED: 'SUBCATEGORY_REQUIRED',
  SUBCATEGORY_NOT_FOUND: 'SUBCATEGORY_NOT_FOUND',
  LOT_NOT_FOND: 'LOT_NOT_FOUND',
  NO_ACCESS: 'NO_ACCESS',
  NOT_OWNER: 'NOT_OWNER',
  USER_ARCHIVED: 'USER_ARCHIVED',
  EMAIL_ALREADY_CONFIRMED: 'EMAIL_ALREADY_CONFIRMED',
  RESEND_CONFIRM_RATE_LIMIT: 'RESEND_CONFIRM_RATE_LIMIT',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_DEACTIVATED: 'USER_DEACTIVATED',
  PASSWORD_RESET_RATE_LIMIT: 'PASSWORD_RESET_RATE_LIMIT',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  REFRESH_TOKEN_MISSING: 'REFRESH_TOKEN_MISSING',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  DUPLICATE_OFFER: 'DUPLICATE_OFFER', // активное предложение на лот уже есть
  MIRROR_OFFER_EXISTS: 'MIRROR_OFFER_EXISTS', // встречное (зеркальное) предложение уже есть
  OFFER_COOLDOWN: 'OFFER_COOLDOWN', // повторное предложение тому же лоту раньше часа
  OFFERED_LOT_NOT_PREFERRED: 'OFFERED_LOT_NOT_PREFERRED', // лот вне предпочтений получателя
  AVATAR_INVALID_FORMAT: 'AVATAR_INVALID_FORMAT', // файл не JPG/PNG
  AVATAR_PROCESSING_ERROR: 'AVATAR_PROCESSING_ERROR', // ошибка при обработке
  AVATAR_NOT_FOUND: 'AVATAR_NOT_FOUND', // попытка удалить отсутствующий аватар
  LAST_ADMIN_DEACTIVATION_FORBIDDEN: 'LAST_ADMIN_DEACTIVATION_FORBIDDEN', // попытка деактивации последнего админа
} as const;

export type ErrorTypes = (typeof ERROR_TYPES)[keyof typeof ERROR_TYPES];
