export const ERROR_TYPES = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_NOT_CONFIRMED: 'EMAIL_NOT_CONFIRMED',
  MAX_SESSIONS_EXCEEDED: 'MAX_SESSIONS_EXCEEDED',
  LOGIN_RATE_LIMIT: 'LOGIN_RATE_LIMIT',
  EMAIL_ALREADY_IN_USE: 'EMAIL_ALREADY_IN_USE',
  LOGIN_ALREADY_IN_USE: 'LOGIN_ALREADY_IN_USE',
  COUNTRY_NOT_FOUND: 'COUNTRY_NOT_FOUND',
  EMAIL_ALREADY_CONFIRMED: 'EMAIL_ALREADY_CONFIRMED',
  RESEND_CONFIRM_RATE_LIMIT: 'RESEND_CONFIRM_RATE_LIMIT',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_DEACTIVATED: 'USER_DEACTIVATED',
  PASSWORD_RESET_RATE_LIMIT: 'PASSWORD_RESET_RATE_LIMIT',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  REFRESH_TOKEN_MISSING: 'REFRESH_TOKEN_MISSING',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  AVATAR_INVALID_FORMAT: 'AVATAR_INVALID_FORMAT', // файл не JPG/PNG
  AVATAR_PROCESSING_ERROR: 'AVATAR_PROCESSING_ERROR', // ошибка при обработке
  AVATAR_NOT_FOUND: 'AVATAR_NOT_FOUND', // попытка удалить отсутствующий аватар
  LAST_ADMIN_DEACTIVATION_FORBIDDEN: 'LAST_ADMIN_DEACTIVATION_FORBIDDEN', // попытка деактивации последнего админа
} as const;

export type ErrorTypes = (typeof ERROR_TYPES)[keyof typeof ERROR_TYPES];
