export enum ChatErrorCode {
  OFFER_NOT_FOUND = 'CHAT_OFFER_NOT_FOUND',
  CHAT_FORBIDDEN = 'CHAT_FORBIDDEN',
  EMPTY_MESSAGE = 'CHAT_EMPTY_MESSAGE',
  ATTACHMENTS_INVALID = 'CHAT_ATTACHMENTS_INVALID',
  TOO_MANY_ATTACHMENTS = 'CHAT_TOO_MANY_ATTACHMENTS',
  ATTACHMENT_NOT_FOUND = 'CHAT_ATTACHMENT_NOT_FOUND',
  FILE_REQUIRED = 'CHAT_FILE_REQUIRED',
  FILE_WRONG_TYPE = 'CHAT_FILE_WRONG_TYPE',
  FILE_TOO_LARGE = 'CHAT_FILE_TOO_LARGE',
  FILE_INFECTED = 'CHAT_FILE_INFECTED',
  FILE_SCAN_FAILED = 'CHAT_FILE_SCAN_FAILED',
  FILE_STORAGE_ERROR = 'CHAT_FILE_STORAGE_ERROR',
}
